spring:
  application:
    name: comments-service
  sql:
    init:
      mode: always

eureka:
  instance:
    hostName: ${spring.application.name}
  client:
    registerWithEureka: true
    serviceUrl: 
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    healthcheck:
      enabled: true
